#!/usr/bin/env ruby

END { Rock.start(ARGV) }

class Rock < Thor
  class_option :mount_root, default: "/media/artm"
  class_option :main_dir, default: "ROCKBOX_4G"
  class_option :podcasts_dir, default: "PODCASTS"
  class_option :podcasts_source, default: "/home/artm/Sync/Pod/podcasts"
  class_option :tracks_glob, default: "*.{mp3,ogg}"
  class_option :keep_available_bytes, default: 500_000
  class_option :config_file, default: "podcasts.yml"

  desc "sync", "Sync podcasts to the player"
  def sync
    copy
    playlists
  end

  desc "copy", "Copy podcasts to the player"
  def copy
    puts "\nMoving podcast episodes to the player"
    select_tracks.tap{|tracks| puts tracks}.each do |track|
      move_file track
    end
  end

  desc "playlists", "Update playlists on the device"
  def playlists
    puts "\nUpdating playlists"
    update_playlists
  end

  desc "unmount", "Unmount the player"
  option :external_dir, default: "MUSIC_8G"
  def umount
    [:main_dir, :external_dir].each do |dir_option|
      path = full_path(dir_option)
      system "umount #{path}" if Dir.exists?(path)
    end
  end

  private

  def full_path *args
    args = [:mount_root] + args
    components = args.map{|arg| options[arg]}
    File.join(*components)
  end

  def main_path
    full_path(:main_dir)
  end

  def select_tracks
    select_total_size_under(incoming_tracks, available_for_podcasts)
  end

  def incoming_tracks
    Dir.glob("#{options[:podcasts_source]}/*/#{options[:tracks_glob]}").sort_by{|track|
      File.mtime(track)
    }
  end

  def rockbox_tracks
    Dir.glob("#{podcasts_destination}/*/#{options[:tracks_glob]}")
  end


  def select_total_size_under tracks, total
    tracks.reduce( [total,[]] ) do |pair,path|
      blocks_left, collected = pair
      file_size = file_size_in_blocks(path)
      return collected unless blocks_left > file_size
      [blocks_left - file_size, collected + [path]]
    end[1]
  end

  def available_for_podcasts
    available_blocks - keep_available_blocks
  end

  def available_blocks
    df_line = %x{df -B #{BLOCK_SIZE} #{podcasts_mount_point}}.split("\n").last
    df_line.split(/ +/)[3].to_i
  end

  def podcasts_mount_point
    File.join(options[:mount_root], options[:main_dir])
  end

  def podcasts_destination
    File.join(podcasts_mount_point, options[:podcasts_dir])
  end

  def keep_available_blocks
    options[:keep_available_bytes] / BLOCK_SIZE
  end

  def file_size_in_blocks path
    File.size(path) / BLOCK_SIZE
  end

  def move_file source
    relative = sanitize_path(relative_path(options[:podcasts_source], source))
    puts "+ #{relative}"
    destination = File.join( podcasts_destination, relative )
    FileUtils.mkdir_p File.dirname destination
    FileUtils.mv source, destination
  end

  def relative_path dir, path
    Pathname(path).relative_path_from(Pathname(dir)).to_s
  end

  def sanitize_path path
    path.gsub(/[»]+/,"_")
  end

  def update_playlists
    groupped = groups.group_tracks rockbox_tracks
    groupped.each do |group, list|
      groupped[group] = spread_by_dirname(list.map{|track| player_path track})
    end
    groupped["podcasts"] = Spread.spread *groupped.values

    FileUtils.mkdir_p playlists_dir
    groupped.each {|group,tracks| save_playlist group, tracks }
  end

  def groups
    @groups ||= (make_group_regexes config["groups"] || {}).extend TrackGroups
  end

  def make_group_regexes groups
    groups.map{|name,patterns| [name,Regexp.union(patterns)]}
  end

  module TrackGroups
    def group_tracks tracks
      tracks.reduce(list_hash) do |groupped,track|
        group = track_group track
        groupped[group] << track
        groupped
      end
    end

    def track_group track
      dir = File.basename File.dirname track
      group, pattern = find{|group,pattern| pattern =~ dir}
      group || "misc"
    end

    def list_hash
      Hash.new {|hash,key| hash[key] = []}
    end
  end

  def spread_by_dirname tracks
    Spread.spread *tracks.group_by{|track| File.dirname track}.values
  end

  def config_file
    File.join podcasts_destination, options[:config_file]
  end

  def load_config
    if File.exists? config_file
      YAML.load_file config_file
    else
      {}
    end
  end

  def config
    @config ||= load_config
  end

  def player_path track
    File.join "/", relative_path(podcasts_mount_point, track)
  end

  def playlists_dir
    File.join podcasts_mount_point, "Playlists"
  end

  def save_playlist group, tracks
    m3u_path = File.join playlists_dir, group + ".m3u"
    puts "%4d tracks @ %s" % [tracks.count, group]
    File.open(m3u_path, "w") { |io| io.puts tracks }
  end

  BLOCK_SIZE = 512
end

BEGIN {
  $LOAD_PATH << File.expand_path("../lib", __FILE__)

  require "bundler/setup"
  require "thor"
  require "yaml"
  require "spread"
}
